services:
  - type: static
    name: mijn-react-app
    env: static
    buildCommand: npm run build
    publishPath: dist        # â† hier je Vite-uitvoer-map
    routes:
      - type: rewrite
        src: /(.*)
        dest: /index.html
